package club.banyuan.blog.mapper;

import club.banyuan.blog.model.TagQuestionRelation;
import club.banyuan.blog.model.TagQuestionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagQuestionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    long countByExample(TagQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int deleteByExample(TagQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int insert(TagQuestionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int insertSelective(TagQuestionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    List<TagQuestionRelation> selectByExample(TagQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    TagQuestionRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TagQuestionRelation record, @Param("example") TagQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int updateByExample(@Param("record") TagQuestionRelation record, @Param("example") TagQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int updateByPrimaryKeySelective(TagQuestionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    int updateByPrimaryKey(TagQuestionRelation record);
}