package club.banyuan.blog.model;

import java.io.Serializable;
import java.util.Date;

public class PrestigeFlow implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.user_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.prestige
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer prestige;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.amount
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.type
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.link_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prestige_flow.created_at
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prestige_flow
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.id
     *
     * @return the value of prestige_flow.id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.id
     *
     * @param id the value for prestige_flow.id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.user_id
     *
     * @return the value of prestige_flow.user_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.user_id
     *
     * @param userId the value for prestige_flow.user_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.prestige
     *
     * @return the value of prestige_flow.prestige
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getPrestige() {
        return prestige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.prestige
     *
     * @param prestige the value for prestige_flow.prestige
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setPrestige(Integer prestige) {
        this.prestige = prestige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.amount
     *
     * @return the value of prestige_flow.amount
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.amount
     *
     * @param amount the value for prestige_flow.amount
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.type
     *
     * @return the value of prestige_flow.type
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.type
     *
     * @param type the value for prestige_flow.type
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.link_id
     *
     * @return the value of prestige_flow.link_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.link_id
     *
     * @param linkId the value for prestige_flow.link_id
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prestige_flow.created_at
     *
     * @return the value of prestige_flow.created_at
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prestige_flow.created_at
     *
     * @param createdAt the value for prestige_flow.created_at
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prestige_flow
     *
     * @mbg.generated Thu Jun 18 19:03:18 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", prestige=").append(prestige);
        sb.append(", amount=").append(amount);
        sb.append(", type=").append(type);
        sb.append(", linkId=").append(linkId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}